INSERT INTO nivel (dir_contenido, nombre) VALUES ('/Lecciones/LAS_PALABRAS_AGUDAS.pdf', 'Palabras Agudas');
INSERT INTO tipo_pregunta (descripcion) VALUES ('Seleccion multiple');
INSERT INTO tipo_pregunta (descripcion) VALUES ('Escrita');
INSERT INTO usuario (Nombre) VALUES ('Mayaka');
INSERT INTO usuario (Nombre) VALUES ('Nagato');
INSERT INTO usuario (Nombre) VALUES ('Matsuri');
INSERT INTO usuario (Nombre) VALUES ('Victorique');
INSERT INTO usuario (Nombre) VALUES ('Nadeko');
INSERT INTO usuario (Nombre) VALUES ('Carlos');
INSERT INTO usuario (Nombre) VALUES ('Julio');